# config.toml

[telegram]
bot_token = "YOUR_BOT_TOKEN"
chat_id = "YOUR_CHAT_ID"

[servers]
server_list = [
    {name = "CERE", ip = "108.181.23.31"},
    {name = "DOT-1", ip = "185.229.64.84"},
    {name = "DOT-2", ip = "5.180.44.21"},
    {name = "DOT-3", ip = "185.229.64.84"},
    {name = "DOT-4", ip = "5.180.44.21"},
    {name = "DOT-9", ip = "185.229.64.84"},
    {name = "DOT-10", ip = "5.180.44.21"},
    {name = "DOT-11", ip = "185.229.64.84"},
    {name = "DOT-12", ip = "5.180.44.21"},
    {name = "DOT-13", ip = "185.229.64.84"},
    {name = "KMA-1", ip = "5.180.44.21"},
    {name = "KMA-2", ip = "185.229.64.84"},
    {name = "KMA-3", ip = "5.180.44.21"},
    {name = "KMA-4", ip = "185.229.64.84"},
    {name = "KSM-1", ip = "5.180.44.21"},
    {name = "KSM-2", ip = "185.229.64.84"},
    {name = "KSM-3", ip = "5.180.44.21"},
    {name = "KSM-4", ip = "185.229.64.84"},
    {name = "KSM-5", ip = "5.180.44.21"},
    {name = "KSM-6", ip = "185.229.64.84"},
    {name = "KSM-7", ip = "5.180.44.21"},
    {name = "KSM-8", ip = "185.229.64.84"},
    {name = "KSM-9", ip = "5.180.44.21"},
    {name = "KSM-10", ip = "185.229.64.84"},
    {name = "KSM-11", ip = "5.180.44.21"},
    {name = "KSM-12", ip = "185.229.64.84"},
    {name = "KSM-13", ip = "5.180.44.21"},
    {name = "KSM-14", ip = "185.229.64.84"},
    {name = "KSM-15", ip = "5.180.44.21"},
    {name = "KSM-17", ip = "185.229.64.84"},
    {name = "KSM-19", ip = "5.180.44.21"},
    {name = "KSM-21", ip = "185.229.64.84"},
    {name = "MYKSM-1", ip = "5.180.44.21"},
    {name = "MYKSM-2", ip = "185.229.64.84"},
    {name = "MYKSM-3", ip = "5.180.44.21"},
    {name = "MYKSM-4", ip = "185.229.64.84"},
    {name = "MYKSM-5", ip = "5.180.44.21"},
    {name = "MYKSM-6", ip = "185.229.64.84"},
    {name = "MYKSM-7", ip = "5.180.44.21"},
    {name = "MYKSM-8", ip = "185.229.64.84"},
    {name = "MYKSM-9", ip = "5.180.44.21"},
    {name = "MYKSM-10", ip = "185.229.64.84"},
    {name = "MYKSM-11", ip = "5.180.44.21"},
    {name = "MYKSM-12", ip = "5.180.44.21"},
    {name = "MYKSM-13", ip = "185.229.64.84"},
    {name = "MYKSM-14", ip = "5.180.44.21"},
    {name = "MYKSM-15", ip = "185.229.64.84"},
    {name = "MYKSM-16", ip = "5.180.44.21"},
    {name = "MYKSM-17", ip = "185.229.64.84"},
    {name = "MYKSM-18", ip = "5.180.44.21"},
    {name = "MYKSM-19", ip = "185.229.64.84"},
    {name = "MYKSM-20", ip = "5.180.44.21"},
    {name = "MYKSM-21", ip = "185.229.64.84"},
    {name = "MYKSM-22", ip = "5.180.44.21"},
    {name = "MYKSM-23", ip = "5.180.44.21"},
    {name = "MYKSM-24", ip = "185.229.64.84"},
    {name = "MYKSM-33", ip = "5.180.44.21"},
    {name = "MYKSM-34", ip = "5.180.44.21"},
    {name = "MYKSM-35", ip = "185.229.64.84"},
    {name = "MYKSM-36", ip = "5.180.44.21"},
    {name = "MYKSM-37", ip = "185.229.64.84"},
    {name = "MYKSM-38", ip = "5.180.44.21"},
    {name = "MYKSM-39", ip = "185.229.64.84"},
    {name = "MYKSM-40", ip = "5.180.44.21"},
    {name = "MYKSM-41", ip = "185.229.64.84"},
    {name = "MYKSM-42", ip = "5.180.44.21"},
    {name = "MYKSM-43", ip = "185.229.64.84"},
    {name = "MYKSM-44", ip = "5.180.44.21"},
    {name = "MYKSM-45", ip = "5.180.44.21"},
    {name = "MYKSM-46", ip = "185.229.64.84"},
    {name = "MYKSM-47", ip = "5.180.44.21"},
    {name = "MYKSM-48", ip = "185.229.64.84"},
    {name = "MYKSM-49", ip = "5.180.44.21"},
    {name = "MYKSM-50", ip = "185.229.64.84"},
    {name = "MYKSM-51", ip = "5.180.44.21"},
    {name = "MYKSM-52", ip = "5.180.44.21"},
    {name = "MYKSM-53", ip = "185.229.64.84"},
    {name = "MYKSM-54", ip = "5.180.44.21"},
    {name = "MYKSM-55", ip = "185.229.64.84"},
    {name = "MYKSM-56", ip = "5.180.44.21"},
    {name = "MYKSM-57", ip = "185.229.64.84"},
    {name = "MYKSM-58", ip = "5.180.44.21"},
    {name = "MYKSM-59", ip = "185.229.64.84"},
    {name = "MYKSM-60", ip = "5.180.44.21"},
    {name = "MYKSM-61", ip = "185.229.64.84"},
    {name = "MYKSM-62", ip = "5.180.44.21"},
    {name = "MYKSM-63", ip = "5.180.44.21"},
    {name = "MYKSM-64", ip = "185.229.64.84"},
    {name = "MYKSM-62", ip = "5.180.44.21"},
    {name = "MYKSM-63", ip = "27.0.232.57"}
]
