# config.toml

[telegram]
bot_token = "YOUR_BOT_TOKEN"
chat_id = "YOUR_CHAT_ID"

[servers]
server_list = [
    {name = "DOT-1", ip = "5.180.44.21"},
    {name = "DOT-2", ip = "185.229.64.84"},
    {name = "DOT-3", ip = "27.0.232.57"}
]
